import {ReactNode} from "react";
import type { Metadata } from "next";
import { Jost } from "next/font/google";

import {Header} from "@/components/simple/header/Header";
import {Footer} from "@/components/simple/footer/Footer";

import './reset.css';
import './global.css';

const jost = Jost({ subsets: ["cyrillic", "latin"] });

export const metadata: Metadata = {
  title: "Camera Shop",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={jost.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
